# Site settings
title: Secret Escapes
locale: de

description: Endlich können wir wieder reisen - vor allem unsere Hotelpartner können es kaum erwarten, Sie als Gäste zu begrüßen. In unserem Video haben wir Hotels, Kollegen und Freunde befragt, um herauszufinden, was alle am meisten vermisst haben und wie sich die Unterkünfte mit der neuen SItuation arrangiert haben, um Ihnen bei Ihrem Aufenthalt Sicherheit zu bieten.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/2020/welcome-back" # the subpath of your site, e.g. /blog/
img:     "/de/2020/welcome-back/_assets/img"
css:     "/de/2020/welcome-back/_assets/css"
js:      "/de/2020/welcome-back/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed